### ISSUE TITLE
[Bare] Todo 기능 구현

### ISSUE THREAD

**Issue by Gr8G1** [Gr8G1/todoapplication#2]
### 만들고자 하는 기능이 무엇인가요?
Todo 기능 구현

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 할일 목록 조회
2. [ ] 할일 목록 등록
3. [ ] 할일 목록 수정
4. [ ] 할일 목록 삭제
5. [ ] 할일 목록 완료

### 예상 작업 시간
1d
